apiVersion: v1
kind: Service
metadata:
  labels:
    app: solace-exporter
  name: solace-exporter
spec:
  ports:
  - name: metrics
    port: 9628
    protocol: TCP
    targetPort: 9628
  selector:
    app: solace-exporter
  type: ClusterIP